# Generated by Django 2.2.4 on 2019-08-21 23:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('airborne', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_num', models.CharField(max_length=3)),
                ('flight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='snakes_on_a_plane_api.Flight')),
            ],
        ),
        migrations.CreateModel(
            name='Passenger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('flight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flight', to='snakes_on_a_plane_api.Flight')),
                ('seat', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='passenger', to='snakes_on_a_plane_api.Seat')),
            ],
        ),
    ]
