# Generated by Django 2.2.4 on 2019-08-21 23:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('snakes_on_a_plane_api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passenger',
            name='seat',
        ),
        migrations.AddField(
            model_name='passenger',
            name='seat_num',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='passenger', to='snakes_on_a_plane_api.Seat'),
        ),
        migrations.AlterField(
            model_name='passenger',
            name='flight',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='flight', to='snakes_on_a_plane_api.Flight'),
        ),
        migrations.AlterField(
            model_name='seat',
            name='flight',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='snakes_on_a_plane_api.Flight'),
        ),
    ]
